//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItemsV
    {
        public int InvoiceItemId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Title { get; set; }
        public string Descrioption { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> IsExpirable { get; set; }
        public string Code1 { get; set; }
        public string Code2 { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<bool> IsReturned { get; set; }
    }
}
