//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string Descrioption { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> MinSalePrice { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Code1 { get; set; }
        public string Code2 { get; set; }
        public string Barcode { get; set; }
        public Nullable<bool> IsExpirable { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<decimal> WholeSalePrice { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
    }
}
