//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string IncomeType { get; set; }
        public string Remarks { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsCheque { get; set; }
        public string ChequeNo { get; set; }
        public string Bank { get; set; }
        public Nullable<System.DateTime> ChequeDueDate { get; set; }
        public Nullable<bool> IsLiquidated { get; set; }
        public Nullable<System.DateTime> LiquidDate { get; set; }
        public string Type { get; set; }
    }
}
