//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorewiseQuantityV
    {
        public int StoreQuantityId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int ProductId { get; set; }
        public string Store { get; set; }
        public Nullable<int> WarehousId { get; set; }
    }
}
